replicaCount: 2

image:
  repository: 428941813622.dkr.ecr.us-east-1.amazonaws.com/lesson-7-django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  # сюди ми на наступному кроці перенесемо env з теми 4
  DEBUG: "False"
  DJANGO_SECRET_KEY: "replace_me"
  
  POSTGRES_DB: app_db
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: app_password
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
